FROM alpine:3.1

# Update
RUN apk add --update python py-pip

# Install app dependencies
RUN pip install Flask
RUN pip install flask_pymongo
RUN pip install datetime
RUN pip install flask-bcrypt

# Bundle app source
COPY BankAPI.py /src/simpleapp.py

EXPOSE  7000
CMD ["python", "/src/simpleapp.py", "-p 7000"]